# Concatenate

In [1]:
%pip install numpy
import numpy as np

Note: you may need to restart the kernel to use updated packages.


In [5]:
roux = np.ones(shape=(3,2))
roux

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [6]:
gumbo = np.ones(shape=(2,2))
gumbo

array([[1., 1.],
       [1., 1.]])

In [9]:
np.concatenate((roux, roux, roux), axis=1)

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [10]:
np.concatenate((roux, roux, roux), axis=0)

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [12]:
np.concatenate((roux, gumbo), axis=0)

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [13]:
np.concatenate((roux, gumbo), axis=1)

ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 3 and the array at index 1 has size 2