# Creating Arrays

In [2]:
%pip install numpy
import numpy as np

Note: you may need to restart the kernel to use updated packages.


In [3]:
np.array(['a', 'b', 'c'])

array(['a', 'b', 'c'], dtype='<U1')

In [5]:
np.array([['a','b'],['c','d'],['e','f']])

array([['a', 'b'],
       ['c', 'd'],
       ['e', 'f']], dtype='<U1')

In [6]:
np.array([[
    ['a','b'], 
    ['c','d'], 
    ['e','f']],
    
    [['g','h'], 
     ['i','j'], 
     ['k','l']]])

array([[['a', 'b'],
        ['c', 'd'],
        ['e', 'f']],

       [['g', 'h'],
        ['i', 'j'],
        ['k', 'l']]], dtype='<U1')

In [9]:
np.zeros(shape=3)


array([0., 0., 0.])

In [10]:
np.zeros(shape=(3,5))


array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [11]:
np.full(shape=(3,5), fill_value='cat')

array([['cat', 'cat', 'cat', 'cat', 'cat'],
       ['cat', 'cat', 'cat', 'cat', 'cat'],
       ['cat', 'cat', 'cat', 'cat', 'cat']], dtype='<U3')

In [12]:
np.arange(start=1, stop=5, step=1)

array([1, 2, 3, 4])

In [13]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
np.random.randint(low=1, high=7, size=(2,3))

array([[6, 3, 2],
       [3, 5, 4]])