# Indexing 1D Arrays

In [1]:
%pip install numpy
import numpy as np

In [3]:
foo = np.array([10, 20, 30, 40, 50])
print(foo)

[10 20 30 40 50]


In [5]:
foo[0]

10

In [6]:
foo[1] = 99

In [7]:
print(foo)

[10 99 30 40 50]


In [11]:
foo[-1]

50

In [12]:
foo[999]

IndexError: index 999 is out of bounds for axis 0 with size 5

In [14]:
foo[[0, 1, 4]]

array([10, 99, 50])

In [15]:
foo[[0,1,0,1]]

array([10, 99, 10, 99])

In [20]:
foo[np.zeros(shape=3, dtype='int64')]

array([10, 10, 10])

In [21]:
foo[:2]

array([10, 99])

In [22]:
foo[2:]

array([30, 40, 50])

In [23]:
foo[::2]

array([10, 30, 50])

In [25]:
foo[[0,1,4]] = [100,200,400]
foo

array([100, 200,  30,  40, 400])

In [26]:
foo[[0,1,4]] = [1,2]

ValueError: shape mismatch: value array of shape (2,) could not be broadcast to indexing result of shape (3,)

In [28]:
foo[[0,1,4]] = 1
foo

array([ 1,  1, 30, 40,  1])