# Infinity

In [1]:
%pip install numpy
import numpy as np

Note: you may need to restart the kernel to use updated packages.


In [3]:
np.array([np.inf, np.NINF])

array([ inf, -inf])

In [4]:
np.array([-1, 1]) / 0

/tmp/ipykernel_18948/1273093014.py:1: RuntimeWarning: divide by zero encountered in divide
  np.array([-1, 1]) / 0


array([-inf,  inf])

In [5]:
np.inf + np.inf

inf

In [6]:
np.inf * 32

inf

In [7]:
np.inf - np.inf

nan

In [8]:
np.inf / np.inf

nan

In [9]:
np.inf == np.inf

True

In [10]:
np.NINF == np.NINF

True

In [11]:
foo = np.array([4, np.inf, 1, np.NINF])

In [12]:
foo == np.inf

array([False,  True, False, False])

In [13]:
foo == np.NINF

array([False, False, False,  True])

In [14]:
np.isposinf(foo)

array([False,  True, False, False])

In [15]:
np.isneginf(foo)

array([False, False, False,  True])

In [16]:
np.isinf(foo)

array([False,  True, False,  True])