# Nan

In [1]:
%pip install numpy
import numpy as np

Note: you may need to restart the kernel to use updated packages.


In [6]:
bot = np.ones(shape=(3,4))
bot[[0, 2], [1, 2]] = np.nan
bot

array([[ 1., nan,  1.,  1.],
       [ 1.,  1.,  1.,  1.],
       [ 1.,  1., nan,  1.]])

In [7]:
bot == np.nan

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [8]:
np.nan == np.nan

False

In [9]:
np.nan != np.nan

True

In [10]:
np.isnan(bot)

array([[False,  True, False, False],
       [False, False, False, False],
       [False, False,  True, False]])

In [11]:
foo =  np.array([1,2,3], dtype=int)
foo[0]= np.nan

ValueError: cannot convert float NaN to integer