# Newaxis

In [1]:
%pip install numpy
import numpy as np

Note: you may need to restart the kernel to use updated packages.


In [4]:
A = np.random.randint(low=1, high=10, size=4)
B = np.random.randint(low=1, high=10, size=3)
A, B


(array([6, 9, 6, 3]), array([9, 6, 6]))

In [9]:
A = A[:, np.newaxis]
B = B[np.newaxis, :]
A, B

(array([[[6]],
 
        [[9]],
 
        [[6]],
 
        [[3]]]),
 array([[9, 6, 6]]))

In [10]:
A - B

array([[[-3,  0,  0]],

       [[ 0,  3,  3]],

       [[-3,  0,  0]],

       [[-6, -3, -3]]])